name = "render-apps-wakeup-cron-worker"
compatibility_date = "2024-04-21"
main = "src/index.ts"

[vars]
API_LIST = "[\"https://gk-app-client.onrender.com\", \"https://gk-app-server.onrender.com/api/v1/health\"]"
MAX_RETRIES = "5"
RETRY_INTERVAL = "30000"

[triggers]
crons = ["*/5 * * * *"] # 每 5 分鐘執行一次

[observability]
enabled = true