name = "render-apps-wakeup-cron-worker"
compatibility_date = "2024-04-21"
main = "src/index.ts"

[vars]
MAX_RETRIES = "5"
RETRY_INTERVAL = "1000"

[triggers]
crons = ["*/5 * * * *"] # 每 5 分鐘執行一次

[observability]
enabled = true