name = "render-apps-wakeup-cron-worker"
compatibility_date = "2024-04-21"
main = "src/index.ts"

[vars]
API_LIST = "[\"https://gk-app-client.onrender.com\", \"https://gk-app-server.onrender.com/api/v1/health\"]"
MAX_RETRIES = "3"
RETRY_INTERVAL = "10000"

[triggers]
crons = ["0 0 * * *"] # 每日 00:00 執行

[observability]
enabled = true